# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: jnorth.photo
email: northcott.j@chisigma.co
version: 1.0.0
author:
  name: Jonathan Northcott
  email: northcott.j@chisigma.co #optional
  website: https://jdnorthcott.com
description: >- # this means to ignore newlines until "baseurl:"
  @nrthco_j's photo evolution since 2010 (curated starting 3.15.2020)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://photos.jdnorthcott.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: northcott-j
instagram_username: nrthco_j

# Build settings
plugins:
  - jekyll-exif-data

image_processing:
  large:
    source: photos/original
    destination: photos/large
    resize_to_limit: [2048, 2048]
    saver:
      strip: true
  thumbnail:
    source: photos/original
    destination: photos/thumbnail
    resize_to_limit: [640, 640]
    saver:
      strip: true
  tint:
    source: photos/original
    destination: photos/tint
    resize_to_fill: [1,1]
    saver:
      strip: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
